language: node_js

cache:
  directories:
  - node_modules # NPM packages

before_script:
  - npm install -g mocha
  - npm install -g eslint

after_success:
  - npm run coveralls

node_js:
  - "6.11.2"
