version: '2'

services:
  kathinka-bot:
    image: node:10.16.0
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: [npm, run, start]
    restart: "always"

  npm:
    image: node:10.16.0
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: [npm, run, test]
